# Default initial positions for the excahauler's ros2_control fake system
initial_positions:
  fork: 0.0
  dump: 0.0
  boom: 0.0
  stick: 0.0
  tilt: 0.0
  arm1: 0.0
  arm2: 0.0
  arm3: 0.0
  arm4: 0.0
  forktip: 0.0
